# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=64, unique=True)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_of_supply', models.CharField(blank=True, max_length=64, null=True)),
                ('buyer_gstin', models.CharField(blank=True, max_length=32, null=True)),
                ('gross_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('round_off_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('CREDIT', 'Credit')], default='CREDIT', max_length=16)),
                ('disclaimers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('mode', models.CharField(max_length=64)),
                ('txn_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sold_uom', models.CharField(choices=[('BASE', 'Base'), ('PACK', 'Pack')], max_length=8)),
                ('rate_per_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('sale_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status', 'invoice_date'], name='sales_sales_status_8766e4_idx'),
        ),
    ]
