# Generated by Django 4.2.25 on 2025-11-07 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        ('customers', '0001_initial'),
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=64, unique=True)),
                ('financial_year', models.CharField(max_length=16, db_index=True)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place_of_supply', models.CharField(max_length=8)),
                ('patient_name', models.CharField(max_length=255, blank=True, null=True)),
                ('patient_age', models.CharField(max_length=16, blank=True, null=True)),
                ('doctor_name', models.CharField(max_length=255, blank=True, null=True)),
                ('doctor_reg_no', models.CharField(max_length=64, blank=True, null=True)),
                ('gross_total', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('discount_total', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('tax_total', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('round_off', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('net_total', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('status', models.CharField(
                    max_length=16,
                    choices=[
                        ('DRAFT', 'Draft'),
                        ('POSTED', 'Posted'),
                        ('CANCELLED', 'Cancelled'),
                    ],
                    default='DRAFT',
                )),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(
                    max_length=16,
                    choices=[
                        ('PAID', 'Paid'),
                        ('PARTIAL', 'Partial'),
                        ('CREDIT', 'Credit'),
                    ],
                    default='CREDIT',
                )),
                ('irn', models.CharField(max_length=128, blank=True, null=True)),
                ('ack_no', models.CharField(max_length=128, blank=True, null=True)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('disclaimers', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

                # 🔗 Foreign keys
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL
                )),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='customers.customer'
                )),
                ('location', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='locations.location'
                )),
                ('posted_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='posted_invoices',
                    to=settings.AUTH_USER_MODEL
                )),
                ('prescription', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='compliance.prescription'
                )),
            ],
        ),

        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(max_digits=14, decimal_places=4)),
                ('free_qty_base', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('sold_uom', models.CharField(max_length=8, choices=[('BASE', 'BASE'), ('PACK', 'PACK')])),
                ('rate_per_base', models.DecimalField(max_digits=14, decimal_places=4)),
                ('discount_percent', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('discount_amount', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('tax_percent', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('tax_amount', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('line_total', models.DecimalField(max_digits=14, decimal_places=4, default=0)),
                ('hsn_code', models.CharField(max_length=64, blank=True, null=True)),
                ('batch_no', models.CharField(max_length=64, blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255, blank=True, null=True)),
                ('pack_text', models.CharField(max_length=128, blank=True, null=True)),
                ('mrp', models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)),
                ('ptr', models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)),
                ('pts', models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)),
                ('requires_prescription', models.BooleanField(default=False)),

                # 🔗 Foreign keys
                ('batch_lot', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='catalog.batchlot'
                )),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='catalog.product'
                )),
                ('sale_invoice', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lines',
                    to='sales.salesinvoice'
                )),
            ],
        ),

        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(max_digits=14, decimal_places=4)),
                ('mode', models.CharField(max_length=64)),
                ('txn_ref', models.CharField(max_length=128, blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL
                )),
                ('sale_invoice', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='payments',
                    to='sales.salesinvoice'
                )),
            ],
        ),

        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status', 'invoice_date'], name='idx_salesinvoice_status_date'),
        ),
    ]
