# Generated by Django 4.2.23 on 2025-11-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-invoice_date']},
        ),
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='round_off',
            new_name='round_off_amount',
        ),
        # migrations.RenameIndex(
        #     model_name='salesinvoice',
        #     new_name='sales_sales_status_8766e4_idx',
        #     old_name='idx_salesinvoice_status_date',
        # ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='ack_date',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='ack_no',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='doctor_reg_no',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='irn',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='free_qty_base',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='pack_text',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='ptr',
        ),
        migrations.RemoveField(
            model_name='salesline',
            name='pts',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='disclaimers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='sold_uom',
            field=models.CharField(choices=[('BASE', 'Base'), ('PACK', 'Pack')], max_length=8),
        ),
    ]
