# Generated by Django 4.2.23 on 2025-11-13 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_idx_salesinvoice_status_date_sales_sales_status_8766e4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='outstanding',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='total_paid',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
