# Generated by Django 5.2.5 on 2025-11-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_outstanding_salesinvoice_total_paid_and_more'),
        ('settingsx', '0004_payment_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='settingsx.paymentmethod'),
        ),
    ]
