# Generated by Django 4.2 on 2025-11-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('settingsx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=16)),
                ('next_number', models.IntegerField(default=1)),
                ('padding_int', models.IntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='drug_license_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pharmacy_license_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='SUCCESS', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
