# Generated by Django 4.2 on 2025-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0002_doccounter_remove_businessprofile_gstin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingKV',
            fields=[
                ('key', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
