# Generated by Django 4.2 on 2025-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0005_paymentmethod_method_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email', models.BooleanField(default=False)),
                ('low_stock_alerts', models.BooleanField(default=False)),
                ('expiry_alerts', models.BooleanField(default=False)),
                ('daily_reports', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('sms_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calc_method', models.CharField(default='INCLUSIVE', max_length=16)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=16)),
                ('invoice_start', models.IntegerField(default=1)),
                ('invoice_template', models.CharField(default='STANDARD', max_length=64)),
                ('invoice_footer', models.CharField(blank=True, max_length=512, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
