# Generated by Django 4.2 on 2025-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0006_notificationsettings_taxbillingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_expiry_days', models.PositiveIntegerField(default=30)),
                ('warning_expiry_days', models.PositiveIntegerField(default=60)),
                ('low_stock_default', models.PositiveIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
