# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SHOP', 'SHOP'), ('WAREHOUSE', 'WAREHOUSE')], default='SHOP', max_length=16)),
                ('address', models.TextField(blank=True)),
                ('state_code', models.CharField(blank=True, max_length=8)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
