# Generated by Django 4.2 on 2025-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
