# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=64)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('RETURNED', 'RETURNED'), ('BLOCKED', 'BLOCKED')], default='ACTIVE', max_length=16)),
                ('recall_reason', models.TextField(blank=True)),
                ('rack_no', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('dosage_strength', models.CharField(blank=True, max_length=64)),
                ('hsn', models.CharField(blank=True, max_length=32)),
                ('schedule', models.CharField(choices=[('OTC', 'OTC'), ('H', 'H'), ('H1', 'H1'), ('X', 'X'), ('NDPS', 'NDPS')], default='OTC', max_length=8)),
                ('pack_size', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='MRP per pack', max_digits=14)),
                ('base_unit', models.CharField(max_length=32)),
                ('pack_unit', models.CharField(max_length=32)),
                ('units_per_pack', models.DecimalField(decimal_places=3, max_digits=14)),
                ('base_unit_step', models.DecimalField(decimal_places=3, default=1.0, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productcategory')),
            ],
        ),
    ]
