# Generated by Django 4.2.23 on 2025-11-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hsn', models.CharField(blank=True, max_length=32)),
                ('schedule', models.CharField(blank=True, max_length=32)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('mrp', models.DecimalField(decimal_places=3, help_text='MRP per pack', max_digits=12)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('base_unit', models.CharField(max_length=32)),
                ('pack_unit', models.CharField(max_length=32)),
                ('units_per_pack', models.DecimalField(decimal_places=3, max_digits=12)),
                ('base_unit_step', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BatchLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('RETURNED', 'RETURNED'), ('BLOCKED', 'BLOCKED')], default='ACTIVE', max_length=16)),
                ('rack_no', models.CharField(blank=True, max_length=64)),
                ('recall_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='batchlot',
            constraint=models.UniqueConstraint(fields=('product', 'batch_no'), name='uq_batch_product_batchno'),
        ),
    ]
