# Generated by Django 4.2 on 2025-11-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_goodsreceiptline_mrp_and_more'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlot',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_strength',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit_step',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, help_text='MRP per pack', max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='schedule',
            field=models.CharField(choices=[('OTC', 'OTC'), ('H', 'H'), ('H1', 'H1'), ('X', 'X'), ('NDPS', 'NDPS')], default='OTC', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_pack',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='batchlot',
            index=models.Index(fields=['product', 'status', 'expiry_date'], name='idx_lot_product_status_exp'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='idx_product_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer'], name='idx_product_mfr'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_product_active'),
        ),
    ]
