# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='batchlot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='idx_product_code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer'], name='idx_product_mfr'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_product_active'),
        ),
        migrations.AddIndex(
            model_name='batchlot',
            index=models.Index(fields=['product', 'status', 'expiry_date'], name='idx_lot_product_status_exp'),
        ),
        migrations.AddConstraint(
            model_name='batchlot',
            constraint=models.UniqueConstraint(fields=('product', 'batch_no'), name='uq_batch_product_batchno'),
        ),
    ]
