# Generated by Django 5.2.8 on 2025-11-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('catalog', '0004_vendor_product_code'),
    ]

    operations = [
    ]
