# Generated by Django 4.2.23 on 2025-11-13 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_0002_initial_0004_vendor_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='batchlot',
            index=models.Index(fields=['status', 'expiry_date'], name='idx_lot_status_exp'),
        ),
        migrations.AddIndex(
            model_name='batchlot',
            index=models.Index(fields=['product', 'expiry_date'], name='idx_lot_product_exp'),
        ),
    ]
