# Generated by Django 4.2 on 2025-11-28 11:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_batchstock'),
        ('catalog', '0007_product_medicine_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchlot',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='batchlot',
            name='initial_quantity_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='batchlot',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='batchlot',
            name='purchase_price_per_base',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='batchlot',
            name='quantity_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_quantity_uoms', to='catalog.uom'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base', to='catalog.uom'),
        ),
        migrations.AddField(
            model_name='product',
            name='rack_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.racklocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_selling', to='catalog.uom'),
        ),
        migrations.AddField(
            model_name='product',
            name='strips_per_box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tablets_per_strip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
