# Generated by Django 4.2.23 on 2025-11-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_invoice_no', models.CharField(blank=True, max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty_packs', models.IntegerField()),
                ('received_base_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('credit_note_no', models.CharField(blank=True, max_length=64)),
                ('credit_note_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot')),
                ('purchase_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseline')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(max_length=32)),
                ('txn_ref', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField()),
                ('received_by', models.CharField(blank=True, max_length=64)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.vendor'),
        ),
    ]
