# Generated by Django 5.2.8 on 2025-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_goodsreceiptline_new_product_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='supplier_type',
            field=models.CharField(choices=[('ONLINE', 'External Website (PDF Import)'), ('OFFLINE', 'Manual Order in ERP')], default='OFFLINE', max_length=16),
        ),
    ]
