# Generated by Django 4.2.23 on 2025-12-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_goodsreceipt_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='medicine_form',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='product',
        ),
    ]
