# Generated by Django 4.2 on 2025-12-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_purchaseorderline_medicine_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='category',
            field=models.CharField(blank=True, help_text="Category ID from frontend (e.g., 'tablet', 'capsule', 'syrup')", max_length=64),
        ),
    ]
