# Generated by Django 4.2.23 on 2025-12-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_purchaseorderline_medicine_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='payment_terms',
        ),
    ]
