# Generated by Django 4.2 on 2025-12-08 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_passwordresetotp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='last_seen_at',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='last_login_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_id'], name='accounts_userdevice_device_idx'),
        ),
    ]
