<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-11-05 13:54
=======
<<<<<<< HEAD
# Generated by Django 4.2.25 on 2025-11-07 06:34
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a

from django.conf import settings
from django.db import migrations, models
<<<<<<< HEAD
import django.db.models.deletion
import django.utils.timezone
=======
=======
# Generated by Django 4.2.23 on 2025-11-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 46f16381a6892573660168f6a14845f0305575bf
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
=======
<<<<<<< HEAD
=======
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
>>>>>>> 46f16381a6892573660168f6a14845f0305575bf
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='RecallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
<<<<<<< HEAD
            name='H1RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NDPSDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='RecallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
                ('reason', models.TextField()),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
<<<<<<< HEAD
=======
>>>>>>> 46f16381a6892573660168f6a14845f0305575bf
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_reg_no', models.CharField(max_length=128)),
                ('prescription_no', models.CharField(max_length=128)),
                ('issue_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='customers.customer')),
=======
<<<<<<< HEAD
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
            ],
        ),
        migrations.CreateModel(
            name='NDPSDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
=======
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_reg_no', models.CharField(max_length=128)),
                ('prescription_no', models.CharField(max_length=128)),
                ('issue_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='NDPSDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
                ('date', models.DateField()),
                ('opening_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('in_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('out_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('closing_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='H1RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name_snapshot', models.CharField(max_length=255)),
                ('batch_no_snapshot', models.CharField(max_length=64)),
                ('expiry_snapshot', models.DateField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_address', models.TextField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_reg_no', models.CharField(max_length=128)),
                ('qty_issued_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('balance_after_issue_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot')),
<<<<<<< HEAD
=======
>>>>>>> 46f16381a6892573660168f6a14845f0305575bf
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
            ],
        ),
    ]
