# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_reg_no', models.CharField(max_length=128)),
                ('prescription_no', models.CharField(max_length=128)),
                ('issue_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='NDPSDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('in_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('out_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('closing_qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='H1RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_no_snapshot', models.CharField(blank=True, max_length=64, null=True)),
                ('expiry_snapshot', models.DateField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_reg_no', models.CharField(blank=True, max_length=128, null=True)),
                ('qty_issued_base', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('balance_after_issue_base', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h1_entries', to='sales.salesinvoice')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesline')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
