# Generated by Django 4.2.23 on 2025-11-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_outstanding_salesinvoice_total_paid_and_more'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='sales.salesinvoice'),
        ),
    ]
