# Generated by Django 4.2.23 on 2025-11-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h1registerentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h1_entries', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesline'),
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
    ]
