# Generated by Django 4.2.23 on 2025-11-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerserializer_remove_customer_address_and_more'),
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h1registerentry',
            name='balance_after_issue_base',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='batch_lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='batch_no_snapshot',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='doctor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='doctor_reg_no',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='drug_name_snapshot',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='expiry_snapshot',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='h1_entries', to='sales.salesinvoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.salesline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='patient_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='patient_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='qty_issued_base',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='closing_qty_base',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='in_qty_base',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='opening_qty_base',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='out_qty_base',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='captured_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_reg_no',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_no',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='valid_till',
            field=models.DateField(default=datetime.date.today),

            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallevent',
            name='batch_lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallevent',
            name='initiated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recallevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recallevent',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallevent',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallevent',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=8),
        ),
    ]
