<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-11-07 08:28
=======
# Generated by Django 4.2.23 on 2025-11-05 15:01
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
<<<<<<< HEAD
        ('compliance', '0003_merge_20251107_1241'),
=======
        ('compliance', '0003_merge_20251105_2029'),
>>>>>>> 38b44f7337d8ae7c8e6818d8f49439bd6ffc151a
    ]

    operations = [
        migrations.AlterField(
            model_name='h1registerentry',
            name='balance_after_issue_base',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='batch_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.batchlot'),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='batch_no_snapshot',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='doctor_reg_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='drug_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='expiry_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h1_entries', to='sales.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesline'),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='qty_issued_base',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
