# Generated by Django 4.2.23 on 2025-11-10 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_batchlot_mfg_date_product_code_product_description_and_more'),
        ('sales', '0001_initial'),
        ('compliance', '0004_alter_h1registerentry_balance_after_issue_base_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='h1registerentry',
            options={'ordering': ['-entry_date']},
        ),
        migrations.AlterModelOptions(
            name='ndpsdailyentry',
            options={'ordering': ['entry_date']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-captured_at']},
        ),
        migrations.AlterModelOptions(
            name='recallevent',
            options={'ordering': ['-initiated_on']},
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='doctor_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='doctor_reg_no',
            new_name='prescriber_reg_no',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='attachment_url',
            new_name='rx_image_url',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='balance_after_issue_base',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='batch_lot',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='batch_no_snapshot',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='doctor_reg_no',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='drug_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='expiry_snapshot',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='line',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='patient_address',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='h1registerentry',
            name='qty_issued_base',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='captured_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_no',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recallevent',
            name='initiated_at',
        ),
        migrations.RemoveField(
            model_name='recallevent',
            name='product',
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='prescriber_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='prescriber_reg_no',
            field=models.CharField(default=0.01, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h1registerentry',
            name='sale_line',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='h1_entries', to='sales.salesline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='closing_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='opening_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='ndpsdailyentry',
            name='qty_issued',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='prescription',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='schedules_captured',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recallevent',
            name='initiated_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.PROTECT, to='accounts.user'),
        ),

        migrations.AddField(
            model_name='recallevent',
            name='initiated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='h1registerentry',
            name='patient_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ndpsdailyentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ndps_entries', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='recallevent',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='ndpsdailyentry',
            unique_together={('entry_date', 'product')},
        ),
        migrations.AlterModelTable(
            name='h1registerentry',
            table='h1_register_entries',
        ),
        migrations.AlterModelTable(
            name='ndpsdailyentry',
            table='ndps_daily_entries',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescriptions',
        ),
        migrations.AlterModelTable(
            name='recallevent',
            table='recall_events',
        ),
        migrations.RemoveField(
            model_name='ndpsdailyentry',
            name='closing_qty_base',
        ),
        migrations.RemoveField(
            model_name='ndpsdailyentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ndpsdailyentry',
            name='in_qty_base',
        ),
        migrations.RemoveField(
            model_name='ndpsdailyentry',
            name='opening_qty_base',
        ),
        migrations.RemoveField(
            model_name='ndpsdailyentry',
            name='out_qty_base',
        ),
        migrations.RemoveField(
            model_name='ndpsdailyentry',
            name='remarks',
        ),
    ]
