# # Generated by Django 4.2.23 on 2025-11-10 12:37

# from django.db import migrations, models
# import django.db.models.deletion
# import django.utils.timezone


# class Migration(migrations.Migration):

#     dependencies = [
#         ('accounts', '0001_initial'),
#         ('compliance', '0005_alter_h1registerentry_options_and_more'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='recallevent',
#             name='initiated_on',
#             field=models.DateField(default=django.utils.timezone.now),
#         ),
#         migrations.AlterField(
#             model_name='recallevent',
#             name='initiated_by',
#             field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
#         ),
#     ]
