# Generated by Django 4.2.23 on 2025-11-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(default='CUS-01', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
