# Generated by Django 4.2.23 on 2025-11-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_merge_20251105_2029'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customer',
        #     name='address',
        # ),
    ]
