# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('rack_code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SALE', 'SALE'), ('ADJUSTMENT', 'ADJUSTMENT'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('RETURN_VENDOR', 'RETURN_VENDOR'), ('WRITE_OFF', 'WRITE_OFF'), ('RECALL_BLOCK', 'RECALL_BLOCK')], max_length=16)),
                ('ref_doc_type', models.CharField(blank=True, max_length=32)),
                ('ref_doc_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.batchlot')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rackrule',
            constraint=models.UniqueConstraint(fields=('location', 'manufacturer_name'), name='uq_rack_location_manufacturer'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['location', 'batch_lot', 'created_at'], name='idx_move_loc_batch_dt'),
        ),
    ]
