# Generated by Django 4.2.23 on 2025-11-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change_base', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SALE', 'SALE'), ('ADJUSTMENT', 'ADJUSTMENT'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('RETURN_VENDOR', 'RETURN_VENDOR'), ('WRITE_OFF', 'WRITE_OFF'), ('RECALL_BLOCK', 'RECALL_BLOCK')], max_length=16)),
                ('ref_doc_type', models.CharField(blank=True, max_length=32)),
                ('ref_doc_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.batchlot')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'batch_lot'], name='idx_ledger_loc_batch')],
            },
        ),
    ]
