# Generated by Django 4.2.23 on 2025-11-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_racklocation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['ref_doc_type', 'ref_doc_id'], name='idx_move_refdoc'),
        ),
    ]
