# Generated by Django 5.2.8 on 2025-11-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_medicine_form'),
        ('inventory', '0004_inventorymovement_idx_move_refdoc'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.batchlot')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location'], name='inventory_b_locatio_5f21e8_idx'), models.Index(fields=['batch'], name='inventory_b_batch_i_202b0b_idx')],
                'unique_together': {('batch', 'location')},
            },
        ),
    ]
