# Generated by Django 4.2.23 on 2025-11-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('eway_bill_no', models.CharField(blank=True, max_length=128, null=True)),
                ('eway_valid_upto', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=64, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('eway_data', models.JSONField(blank=True, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('IN_TRANSIT', 'IN_TRANSIT'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='DRAFT', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfer_vouchers', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out_vouchers', to='locations.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_transfer_vouchers', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in_vouchers', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='catalog.batchlot')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transfervoucher')),
            ],
        ),
        migrations.AddIndex(
            model_name='transfervoucher',
            index=models.Index(fields=['status', 'created_at'], name='idx_transf_status_created'),
        ),
        migrations.AddIndex(
            model_name='transferline',
            index=models.Index(fields=['voucher'], name='idx_transferline_voucher'),
        ),
    ]
