# Generated by Django 4.2.23 on 2025-11-10 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfervoucher',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='transfervoucher',
            new_name='idx_transfer_status_created',
            old_name='idx_transf_status_created',
        ),
        migrations.RemoveField(
            model_name='transfervoucher',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='transfervoucher',
            name='eway_bill_no',
        ),
        migrations.RemoveField(
            model_name='transfervoucher',
            name='eway_valid_upto',
        ),
        migrations.RemoveField(
            model_name='transfervoucher',
            name='vehicle_no',
        ),
        migrations.AlterField(
            model_name='transfervoucher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transfervoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16),
        ),
    ]
