# Generated by Django 4.2.23 on 2025-11-11 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SALES_REGISTER', 'Sales Register'), ('H1_REGISTER', 'H1 Register'), ('NDPS_DAILY', 'NDPS Daily'), ('STOCK_LEDGER', 'Stock Ledger')], max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status', 'created_at'], name='reports_rep_report__697d1b_idx')],
            },
        ),
    ]
