# Generated by Django 4.2.23 on 2025-11-05 13:54

# Generated by Django 4.2.25 on 2025-11-07 06:34

# Generated by Django 4.2.23 on 2025-11-05 13:54


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SALES_REGISTER', 'SALES_REGISTER'), ('H1_REGISTER', 'H1_REGISTER'), ('NDPS_DAILY', 'NDPS_DAILY'), ('STOCK_LEDGER', 'STOCK_LEDGER')], max_length=32)),
                ('params', models.JSONField()),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], db_index=True, default='QUEUED', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
