<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-11-27 10:36
=======
# Generated by Django 5.2.8 on 2025-11-27 09:39
>>>>>>> 3e0c97f5579f789fc80038ba24db3dbd2a62c8d5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexport',
            name='report_type',
            field=models.CharField(choices=[('SALES_REGISTER', 'Sales Register'), ('H1_REGISTER', 'H1 Register'), ('NDPS_DAILY', 'NDPS Daily'), ('STOCK_LEDGER', 'Stock Ledger'), ('EXPIRY_STATUS', 'Expiry Status Report'), ('TOP_SELLING', 'Top Selling Report')], max_length=32),
        ),
    ]
